[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    authentication: Authentication endpoint tests
    user: User CRUD endpoint tests
    role: Role CRUD endpoint tests
    booking_session: Booking Session CRUD endpoint tests
    menu: Menu CRUD endpoint tests
    food_package: Food Package CRUD endpoint tests
    booking: Booking CRUD endpoint tests

